// src/utils/sampleData.ts
import { Question } from '../types';

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: 'q001',
    subject: 'Anesteziyoloji',
    topic: 'Genel Anestezi',
    year: 2023,
    difficulty: 'orta',
    text: 'Propofol infüzyon sendromu aşağıdakilerden hangisi ile karakterizedir?',
    options: [
      { id: 'A', text: 'Hiperglisemi, metabolik alkaloz, rabdomiyoliz' },
      { id: 'B', text: 'Metabolik asidoz, rabdomiyoliz, kardiyak disfonksiyon' },
      { id: 'C', text: 'Hipoglisemi, respiratuar asidoz, miyoglobinüri' },
      { id: 'D', text: 'Hiperkalemi, metabolik alkaloz, kardiyak asistol' },
      { id: 'E', text: 'Hiponatremi, laktik asidoz, hipertansiyon' },
    ],
    correctOptionId: 'B',
    explanation: 'Propofol infüzyon sendromu (PRIS) nadir fakat ölümcül bir komplikasyondur. Yüksek doz (>4 mg/kg/sa) veya uzun süreli propofol infüzyonu ile ortaya çıkar. Klinik tablo: metabolik asidoz (laktik asidoz), rabdomiyoliz (CK yüksekliği, miyoglobinüri), kardiyak disfonksiyon (yeni LBBB, ST elevasyonu, bradikardi), karaciğer yağlanması, hipertrigliseridemi, akut böbrek yetmezliği ile karakterizedir. Tedavi: propofol kesilmesi, destekleyici tedavi.',
    tags: ['propofol', 'PRIS', 'yoğun bakım', 'komplikasyon'],
  },
  {
    id: 'q002',
    subject: 'Anesteziyoloji',
    topic: 'Rejyonel Anestezi',
    year: 2023,
    difficulty: 'zor',
    text: 'Lokal anestezik sistemik toksisitesinde (LAST) kardiyotoksisite tedavisinde ilk tercih edilmesi gereken ajan aşağıdakilerden hangisidir?',
    options: [
      { id: 'A', text: 'Epinefrin yüksek doz (>1 mcg/kg)' },
      { id: 'B', text: 'Amiodarone 300 mg IV' },
      { id: 'C', text: 'Lipid emülsiyon (%20) 1.5 mL/kg bolus' },
      { id: 'D', text: 'Sodyum bikarbonat 1-2 mEq/kg' },
      { id: 'E', text: 'Vazopressin 40 IU IV' },
    ],
    correctOptionId: 'C',
    explanation: 'LAST tedavisinde kardiyak arrest geliştiğinde %20 lipid emülsiyon (İntralipid) 1.5 mL/kg IV bolus uygulanır, ardından 0.25 mL/kg/dk infüzyon başlanır. Lipid emülsiyon "lipid sink" mekanizması ile lokal anesteziği plazma ve dokudan sekestre eder. Epinefrin düşük doz (<1 mcg/kg) kullanılmalıdır; yüksek doz ROSC sonrası ventriküler fibrilasyon riskini artırır. ASRA LAST kılavuzlarına göre benzodiazepinler konvülsiyon için tercih edilirken, propofol lipid tedavisinin yerine geçmez.',
    tags: ['LAST', 'lipid emülsiyon', 'bupivakain', 'rejyonel anestezi'],
  },
  {
    id: 'q003',
    subject: 'Anesteziyoloji',
    topic: 'Nöroanestezi',
    year: 2022,
    difficulty: 'orta',
    text: 'İntrakranyal basınç artışında serebral perfüzyon basıncını (CPP) korumak için aşağıdakilerden hangisi yanlıştır?',
    options: [
      { id: 'A', text: 'MAP 60-70 mmHg\'nin üzerinde tutulmalıdır' },
      { id: 'B', text: 'PaCO2 30-35 mmHg hedeflenmelidir' },
      { id: 'C', text: 'Head-up pozisyon (30°) venöz drenajı artırır' },
      { id: 'D', text: 'Mannitol osmotik diürezi ile ICP\'yi düşürür' },
      { id: 'E', text: 'Hiperventilasyon uzun süreli ICP kontrolünde tercih edilir' },
    ],
    correctOptionId: 'E',
    explanation: 'Uzun süreli hiperventilasyon (PaCO2 <30 mmHg) ICP kontrolünde tercih edilmez. Hiperventilasyon vazokonstruksiyon yaparak akut ICP yükselişlerinde geçici olarak kullanılabilir (4-6 saat), ancak serebral iskemi riski nedeniyle uzun süreli uygulanmamalıdır. CPP = MAP - ICP formülü ile hesaplanır, hedef CPP >60 mmHg\'dir. Diğer şıklar doğrudur: MAP korunmalı, normokapni (PaCO2 35-40) veya hafif hipokapni (30-35) kullanılabilir, 30° head-up venöz drenajı iyileştirir, mannitol (0.5-1 g/kg) etkili bir ICP düşürücüdür.',
    tags: ['ICP', 'CPP', 'nöroanestezi', 'hiperventilasyon'],
  },
  {
    id: 'q004',
    subject: 'Dahiliye',
    topic: 'Kardiyoloji',
    year: 2023,
    difficulty: 'orta',
    text: 'Akut MI sonrası gelişen ventriküler septal defekt (VSD) için aşağıdakilerden hangisi doğrudur?',
    options: [
      { id: 'A', text: 'Genellikle anterior MI\'dan 2-5 gün sonra gelişir' },
      { id: 'B', text: 'İntraaortik balon pompası kesinlikle kontrendikedir' },
      { id: 'C', text: 'Semptomatik olmayan hastalarda cerrahi gerekmez' },
      { id: 'D', text: 'Sağ kalp kateterizasyonunda oksijen saturasyon "step-up" yoktur' },
      { id: 'E', text: 'Papiller kas rüptüründen klinik olarak ayırt edilemez' },
    ],
    correctOptionId: 'A',
    explanation: 'Mekanik komplikasyonlar içinde VSD genellikle anterior (LAD) veya inferior (RCA) MI sonrası 3-5. günde (reperfüzyon öncesi çağda) veya fibrinolitik tedavi ile daha erken görülebilir. Sağ kalp kateterizasyonunda sağ ventrikülde/pulmoner arterde oksijen saturasyon "step-up" saptanması tanıyı doğrular. İntraaortik balon pompası afterload azaltarak tedaviye yardımcı olur (kontrendike değildir). Tüm mekanik VSD\'ler, semptom olsun ya da olmasın cerrahi/perkütan kapatma gerektirir. Papiller kas rüptüründen murmur karakteri (holosistolik VSD vs sistolik MR) ve eko ile ayırt edilebilir.',
    tags: ['MI komplikasyonu', 'VSD', 'mekanik komplikasyon'],
  },
  {
    id: 'q005',
    subject: 'Pediatri',
    topic: 'Yenidoğan',
    year: 2022,
    difficulty: 'kolay',
    text: 'Respiratuar distres sendromu (RDS) olan prematüre bebekte surfaktan tedavisi için aşağıdakilerden hangisi doğrudur?',
    options: [
      { id: 'A', text: 'Surfaktan tedavisi yalnızca profilaktik olarak uygulanır' },
      { id: 'B', text: 'Beraktan (poraktant alfa) 100 mg/kg intratrakeal verilir' },
      { id: 'C', text: 'Surfaktan tedavisi 34 hafta üzerindeki preterm bebeklerde endikedir' },
      { id: 'D', text: 'INSURE tekniği non-invazif ventilatuar desteği önler' },
      { id: 'E', text: 'Surfaktan tedavisi sonrası steroid uygulaması zorunludur' },
    ],
    correctOptionId: 'B',
    explanation: 'Poraktant alfa (Curosurf/Beraktan) dozu 100-200 mg/kg intratrakeal olarak uygulanır. Surfaktan hem profilaktik (<27 hafta) hem kurtarıcı (RDS gelişen bebeklerde) olarak kullanılabilir. INSURE (INtubate-SURfactant-Extubate) tekniği ile surfaktan verildikten sonra bebek ekstübe edilerek non-invazif CPAP\'a alınır; mekanik ventilasyon ihtiyacını azaltır, tamamen önlemez. Endikasyon <34 hafta veya klinik RDS varlığıdır. Surfaktan sonrası rutin steroid uygulaması gerekmez.',
    tags: ['RDS', 'surfaktan', 'prematüre', 'yenidoğan'],
  },
  {
    id: 'q006',
    subject: 'Farmakoloji',
    topic: 'Opioidler',
    year: 2023,
    difficulty: 'zor',
    text: 'Remifentanil için aşağıdakilerden hangisi yanlıştır?',
    options: [
      { id: 'A', text: 'Ester yapısında olup plazma ve doku kolinesterazları tarafından metabolize edilir' },
      { id: 'B', text: 'Bağımsız eliminasyon yarı ömrü yaklaşık 3-10 dakikadır' },
      { id: 'C', text: 'Böbrek yetmezliğinde doz ayarlaması gerekmez' },
      { id: 'D', text: 'Akut opioid toleransı ve hiperaljeziye yol açabilir' },
      { id: 'E', text: 'Sefentanil ile karşılaştırıldığında daha fazla kas rijiditesi yapar' },
    ],
    correctOptionId: 'E',
    explanation: 'Remifentanil kas rijiditesi (göğüs duvarı sertliği) açısından diğer opioidlere benzer, sefentanilden daha fazla yapmaz; hız bağımlıdır (hızlı bolus riski artırır). Diğer şıklar doğrudur: remifentanil ester yapıdadır, nonspesifik plazma ve doku esterazları (kolinesteraz değil, karboksilesterazlar) tarafından hidrolize edilir; eliminasyon yarı ömrü 3-10 dakikadır ve organ yetmezliğinden etkilenmez (böbrek ve karaciğer yetmezliğinde doz ayarı gerekmez). Önemli bir dezavantajı akut tolerans ve opioid kaynaklı hiperaljezi (OIH) yapabilmesidir.',
    tags: ['remifentanil', 'farmakoloji', 'opioid', 'anestezi'],
  },
  {
    id: 'q007',
    subject: 'Biyokimya',
    topic: 'Enzimler',
    year: 2021,
    difficulty: 'kolay',
    text: 'Akut miyokard enfarktüsünde en erken yükselen biyobelirteç hangisidir?',
    options: [
      { id: 'A', text: 'Troponin I' },
      { id: 'B', text: 'CK-MB' },
      { id: 'C', text: 'Miyoglobin' },
      { id: 'D', text: 'LDH' },
      { id: 'E', text: 'AST' },
    ],
    correctOptionId: 'C',
    explanation: 'Miyoglobin akut MI\'da en erken yükselen belirteçtir (1-3 saat içinde), ancak kardiyak spesifisitesi düşüktür (iskelet kasından da salınır). Troponin I ve T ise 4-6 saatte yükselir, 24 saatte pik yapar ve 7-14 güne kadar yüksek kalır; kardiyak hasarın altın standardıdır. CK-MB 4-6 saatte yükselir, 24 saatte pik yapar. LDH ve AST geç yükselen belirteçlerdir (6-12 saat, pik 24-48 saat).',
    tags: ['MI', 'troponin', 'miyoglobin', 'biyobelirteç'],
  },
  {
    id: 'q008',
    subject: 'Genel Cerrahi',
    topic: 'Akut Karın',
    year: 2022,
    difficulty: 'orta',
    text: 'Akut apandisit için Alvarado skoru hesaplanırken aşağıdakilerden hangisi 2 puan değerindedir?',
    options: [
      { id: 'A', text: 'Sağ alt kadran hassasiyeti' },
      { id: 'B', text: 'Ateş (>37.3°C)' },
      { id: 'C', text: 'Bulantı/kusma' },
      { id: 'D', text: 'Lökositoz (>10.000)' },
      { id: 'E', text: 'Reboun tenderness' },
    ],
    correctOptionId: 'D',
    explanation: 'Alvarado skoru (MANTRELS): M-Migration of pain (göç) 1pt, A-Anorexia 1pt, N-Nausea/vomiting 1pt, T-Tenderness in RLQ (sağ alt kadran hassasiyeti) 2pt, R-Rebound tenderness 1pt, E-Elevated temperature 1pt, L-Leukocytosis (lökositoz >10.000) 2pt, S-Shift to left (sola kayma) 1pt. Toplam 10 puan. Sağ alt kadran hassasiyeti ve lökositoz 2\'şer puan değerindedir. ≥7 puan: yüksek olasılık (cerrahi).',
    tags: ['apandisit', 'Alvarado', 'akut karın', 'cerrahi'],
  },
  {
    id: 'q009',
    subject: 'Kadın-Doğum',
    topic: 'Obstetrik',
    year: 2023,
    difficulty: 'zor',
    text: 'Preeklampside şiddetli bulguların aşağıdakilerden hangisi yanlış verilmiştir?',
    options: [
      { id: 'A', text: 'Sistolik KB ≥160 mmHg veya diastolik ≥110 mmHg' },
      { id: 'B', text: 'Trombositopeni (<100.000/μL)' },
      { id: 'C', text: 'Kreatinin >1.1 mg/dL veya bazal değerin 2 katı' },
      { id: 'D', text: 'Yeni başlayan baş ağrısı veya görme bozukluğu' },
      { id: 'E', text: 'Proteinüri ≥1 g/24 saat' },
    ],
    correctOptionId: 'E',
    explanation: 'ACOG 2013 revize kriterlerine göre şiddetli preeklampsi için proteinüri miktarı artık tanı kriteri değildir. Şiddetli bulguların kriterleri: KB ≥160/110 mmHg (en az 4 saat arayla 2 ölçüm), trombositopeni <100.000/μL, karaciğer enzim yüksekliği (2 katı), şiddetli epigastrik/sağ üst kadran ağrısı, kreatinin >1.1 mg/dL veya bazalın 2 katı, pulmoner ödem, yeni nörolojik semptomlar. Proteinüri miktarı (2+ veya >5 g/24 sa eski kriter) artık "şiddetli" tanımlayıcısı olarak kullanılmaz.',
    tags: ['preeklampsi', 'obstetrik', 'şiddetli preeklampsi', 'ACOG'],
  },
  {
    id: 'q010',
    subject: 'Fizyoloji',
    topic: 'Solunum Fizyolojisi',
    year: 2022,
    difficulty: 'orta',
    text: 'V/Q mismatch açısından aşağıdakilerden hangisi doğrudur?',
    options: [
      { id: 'A', text: 'Ölü boşluk ventilasyon-perfüzyon oranının sıfıra yaklaştığı alandır' },
      { id: 'B', text: 'Şant PaO2\'yi düşürür ancak PaCO2\'yi değiştirmez' },
      { id: 'C', text: 'Yüksek FiO2 uygulaması şant hipoksemisini tamamen düzeltir' },
      { id: 'D', text: 'Normal akciğerde apikal V/Q oranı bazale göre daha düşüktür' },
      { id: 'E', text: 'V/Q mismatch hipokseminin en sık nedenidir' },
    ],
    correctOptionId: 'E',
    explanation: 'V/Q mismatch (ventilasyon-perfüzyon uyumsuzluğu) klinik hipokseminin en sık nedenidir. Ölü boşluk: ventilasyon var, perfüzyon yok (V/Q → ∞). Şant: perfüzyon var, ventilasyon yok (V/Q → 0). Normal akciğerde apikal bölgede V/Q oranı ~3 (ventilasyon görece fazla), bazalde ~0.6\'dır; apex V/Q oranı bazale göre YÜKSEK. Şant hipoksemisinde PaO2 düşer VE PaCO2 yükselebilir; saf şantta yüksek FiO2 ile PaO2 tam düzelmez (şanttan gelen kanın oksijenasyonu sağlanamaz).',
    tags: ['V/Q', 'şant', 'ölü boşluk', 'hipoksi', 'solunum fizyolojisi'],
  },
];
